import type { Metadata } from "next";
import "./globals.css";
import Header from "./header/page";
import { StudentContextProvider } from "./contexts/student-context";
import Footer from "./footer/page";
import { AuthContextProvider } from "./contexts/auth-context";
import { CourseContextProvider } from "./contexts/course-context";
import { ContentContextProvider } from "./contexts/content-context";

export const metadata: Metadata = {
	title: "Student Management App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className="h-full">
			<body className="flex flex-row justify-center items-center h-full bg-background text-textprimary">
				<AuthContextProvider>
					<StudentContextProvider>
						<CourseContextProvider>
							<ContentContextProvider>
								<div className="flex flex-col h-full py-5 w-full max-w-7xl">
									<Header />
									<div className={`bg-surface flex-grow overflow-y-auto`}>
										{children}
									</div>
									<Footer />
								</div>
							</ContentContextProvider>
						</CourseContextProvider>
					</StudentContextProvider>
				</AuthContextProvider>
			</body>
		</html>
	);
}
